# Multi-CPU Configuration File
# Adjust these values based on your HPC setup and SLURM parameters

[cpu]
# Number of CPUs (should match SLURM -c parameter)
num_cpus = 2

# Total cores across all CPUs (should match SLURM -n parameter)
# This is the total number of worker threads that will be spawned
cores_per_cpu = 8

# Enable NUMA-aware processing
enable_numa = true

[processing]
# Maximum number of precursors to process
max_precursors = 8000

# Fragment repeat number
frag_repeat_num = 5

# Output directory for results
output_dir = "output_precursors"

[performance]
# Enable performance monitoring
monitor_cpu_usage = true

# Print progress every N precursors
progress_interval = 100

# Work queue buffer size (0 = unbounded)
queue_buffer_size = 0