# Multi-CPU Configuration File
# Configuration: 4 CPUs × 4 cores per CPU = 16 total threads

[cpu]
# Number of CPUs (SLURM -c parameter)
num_cpus = 4

# Cores per CPU (SLURM -n parameter)
# Total worker threads = num_cpus × cores_per_cpu = 4 × 4 = 16
cores_per_cpu = 4

# Enable NUMA-aware processing
enable_numa = true

[processing]
# Maximum number of precursors to process
max_precursors = 8000

# Fragment repeat number
frag_repeat_num = 5

# Output directory for results
output_dir = "output_precursors"

[performance]
# Enable performance monitoring
monitor_cpu_usage = true

# Print progress every N precursors
progress_interval = 100

# Work queue buffer size (0 = unbounded)
queue_buffer_size = 0
